### ISSUE TITLE
Get InstancePostProcessor in sync with *Callbacks

### ISSUE THREAD

**Issue by debruyckere** [junit-team/junit-lambda#21]
It seems the InstancePostProcessor could be made in sync with all the Callbacks, and probably be named TestCallbacks, giving it both a pre and post method similar to the other Callbacks.

An example use case is measuring how long the execution of the test method took (without all before/after calls). We use this to measure the performance of our code, and fail the test if it runs significantly slower than earlier executions.

**Comment by sbrannen** [comment]
@debruyckere,

I'm not quite sure what you mean by "in sync with the other callbacks".

For starters, it does not make sense to introduce a "pre" callback for `InstancePostProcessor`. The sole purpose of the `InstancePostProcessor` API is to allow extension developers to post-process the test instance (i.e., the object itself), and you cannot pre-process something that does not yet exist. In other words, you cannot process an object before it has been instantiated.

Regarding measuring the execution time of a test method without `@BeforeEach` and `@AfterEach` methods, that is already possible with `BeforeEachCallbacks` and `AfterEachCallbacks`. Please see [TimingExtension](https://github.com/junit-team/junit-lambda/blob/master/sample-extension/src/main/java/com/example/timing/TimingExtension.java) and [TimingExtensionTests](https://github.com/junit-team/junit-lambda/blob/master/sample-extension/src/test/java/com/example/timing/TimingExtensionTests.java) for details.

If this addresses your concerns, please let us know so that we can close this issue.

Thanks,

Sam

**Comment by debruyckere** [comment]
Sorry, I misunderstood. It's clear now.
