### ISSUE TITLE
Split TestDescriptor into two interfaces

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit-lambda#33]
- `TestDescriptor`: immutable API for users of Launcher (in junit-engine-api)
- `MutableTestDescriptor` extends `TestDescriptor`: additional methods to add children etc.

**Comment by kcooney** [comment]
I would prefer a builder. `TestDescriptor` can have a `builder()` static method and a `toBuilder()` instance method.

**Comment by sbrannen** [comment]
Hi Kevin,

A builder wouldn't help us in this particular situation. The current contract of the `TestDescriptor` interface in the prototype contains methods for mutating the state of a descriptor (e.g., `addChild(TestDescriptor)` and `removeChild(TestDescriptor)`). This was, however, never the intention. These types of methods were only added in order to allow the team to make quick progress with the prototype. Now that the prototype phase is over, we are therefore removing such leaky abstractions.

Make sense?

**Comment by dsaff** [comment]
@sbrannen, when will the MutableTestDescriptor be used, then?

**Comment by jlink** [comment]
> Am 02.12.2015 um 22:23 schrieb David Saff <notifications@github.com>:
> @sbrannen, when will the MutableTestDescriptor be used, then?
> 
During the build phase of the test descriptors tree, currently called "test discovery phase". Usage might be hidden behind some kind of builder but unless you want to do it in two phases, you'll have to mutate (add children to) an existing descriptor at some point. Maybe you have different proposal?
