### ISSUE TITLE
ReflectionUtils.handleException() should not wrap a target exception in an IllegalStateException

### ISSUE THREAD

**Issue by jlink** [junit-team/junit-lambda#64]
## Status Quo

The `handleException()` method in `ReflectionUtils` currently extracts a _target exception_ from an `InvocationTargetException`, and if the _target exception_ is a checked `Exception` it will be wrapped in an `IllegalStateException` with the message `"Unhandled exception"`.

This behavior, however, is inappropriate for a testing framework that reflectively invokes test methods.

Specifically, any exception thrown by a test method must be reported in `TestExecutionResult`. If such an exception is wrapped in an `IllegalStateException`, that makes it very difficult to _retrieve_ the original exception, since it is impossible to know that some `IllegalStateExceptions` should be treated differently than others.

## Analysis

We do not want to have to reason about the contents of an `IllegalStateException`. Instead, we need an explicit way to retrieve an exception thrown by a test method.

## Deliverables

- [x] Change everything that `throws Throwable` to `throws Exception`
- [x] Change ReflectionUtlils.invokeMethod()/newInstance() to _mask_ checked exceptions as unchecked exceptions without physically wrapping them in a `RuntimeException`.
- [x] Refactor `ReflectionUtils.handleException()` accordingly.

**Comment by sbrannen** [comment]
Thanks for raising this issue.

I've been aware of it for quite some time; I just didn't get around to creating a ticket for it.

We actually do not want to propagate an `InvocationTargetException` since it is a checked exception. Instead, we should wrap either the `InvocationTargetException` or its _target exception` in a custom `RuntimeException` that we can then correctly handle higher up the call stack.

**Comment by sbrannen** [comment]
I have completely revised this issue's title and description.

**Comment by jlink** [comment]
I'm just about adding some tests for correct exception propagation in the engine. Fixing the tests will force me to come up with a proposal.

**Comment by jlink** [comment]
What's the problem with a checked exception? If we have to catch exceptions when calling invoke anyway, we could even throw Throwsble...

**Comment by marcphilipp** [comment]
I assumed it would be sufficient to rethrow the target exception. Why would we want to wrap it?

**Comment by sbrannen** [comment]
Hi guys,

Those are naturally very valid questions.

The question here is a fundamental one: namely, should our utility classes throw checked exceptions?

Bear in mind that throwing checked exceptions forces the caller to either catch the exception (and potentially handle it incorrectly), declare it and allow it to propagate, or catch it and rethrow it wrapped in an unchecked exception (which may be a type we do not recognize -- which is currently the case for `ReflectionUtils.invokeMethod` since it wraps the exception in an `IllegalStateException`).

We also need to keep in mind that declaring that checked exceptions are thrown will limit the ease with which we can use such utility classes in lambda expressions.

In order to promote composability of lambda expressions and simultaneously to avoid that intermediate code in the call stack can incorrectly handle checked exceptions thrown by user code, I think it's worth implementing a _wrapping_ `RuntimeException` that we can react to correctly at the appropriate level in the call stack. If we later determine that this style of exception handling does not suit our needs, we could then switch to throwing checked exceptions from certain methods in `ReflectionUtils`.

my 2¢

**Comment by jlink** [comment]
2015-12-18 15:21 GMT+01:00 Marc Philipp <notifications@github.com>:

> I assumed it would be sufficient to rethrow the target exception. Why
> would we want to wrap it?
>

That was my assumption as well.

Have a look at my last commit
https://github.com/junit-team/junit-lambda/commit/12bbe5afc72f457e5bba4bbcf68c49d6e4b77a4e:

- I took up Sam's advice and wrapped the exception in
ReflectionUtils.TargetExceptionWrapper
- I added a test suite for checking if checked and unchecked exception are
properly reported: ExceptionHandlingTests
- The wrapping forced me to introduce additional catch statements in 6
places :(

I guess that getting rid of the wrapper and just throwing the raw Throwable
instead will simplify the code. Some other users of
ReflectionUtils.handleException() might have to change as a consequence,
though.

**Comment by jlink** [comment]
See my other post.

Having an unchecked wrapper leaves it up to us whether we remeber to catch
ExceptionWrapper or not. Since we should do that most of the time - I'd say
always but have learnt that always is udually once too often - a checked
exception could be the best choice in this special case. Our ExtensionPoint
interfaces for example use "throw Throwable" anyway to allow users to not
care if they throw exceptions.

2015-12-18 15:54 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by jlink** [comment]
Added pull request to show how both solutions compare: https://github.com/junit-team/junit-lambda/pull/77

**Comment by sbrannen** [comment]
Checked exceptions thrown by `invokeMethod()` and `newInstance()` in `ReflectionUtils` are now _masked_ as unchecked exceptions via a reflective hack. See the linked commits for details.

See also: #83
