### ISSUE TITLE
Ensure junit5Test is executed by 'gradle test' task

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit-lambda#85]

**Comment by jlink** [comment]
Doesn't it work?

2016-01-04 14:47 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by sbrannen** [comment]
> Doesn't it work?

No, not before my last commit.

The following line existed in `build.gradle`:

```
test.enabled = false
```

But I've fixed it now.

`gradle test` now depends on the `junit5Test` task (at least manually configured within `build.gradle` for the `junit-tests` module).

**Comment by jlink** [comment]
> 2016-01-04 14:58 GMT+01:00 Sam Brannen <notifications@github.com>:
> > Doesn't it work?
> No, not before my last commit. Strange. It worked on my machine :-/

Are you sure that a clean gradle build wouldn't run "junit5Test" ? It's
skipped when it's already up to date.

> The following line existed in build.gradle:
>
> test.enabled = false
>
> But I've fixed it now.
>
> gradle test now depends on the junit5Test task (at least manually
> configured within build.gradle for the junit-tests module).
>

This shouldn't be necessary because the gradle plugin adds 'junit5Test' as
dependency of 'check' which itself is a dependency of 'test'. Something
doesn't work as expected. I'll also have a look.

**Comment by marcphilipp** [comment]
I've added that line to `build.gradle` after migrating all tests to JUnit 5. By default, the `junit5Test` task depends on `check`, not `test`, so `gradle check` did execute `junit5Test`. But it feels good to me that now `gradle test` will also run them. Maybe we should enable that behavior by default?

**Comment by jlink** [comment]
OK, I'll make the dependency in the plugin on "test" instead of on "check"
and remove

    test.dependsOn(junit5Test)

in junit-tests/build.gradle




2016-01-04 15:10 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by jlink** [comment]
Or maybe not. The thing is that "test" actually meand "junit4Test" (or
testngTest). But if junit5Test also handles junitTest, I have to remove the
dependency of check on test so that junit4 tests are not being run twice.

I'll leave it as is.

2016-01-04 15:15 GMT+01:00 Johannes Link <jl@johanneslink.net>:

**Comment by sbrannen** [comment]
As the subject implies, the point of this issue was to have `gradle test` run `junit5Test`, which IMO is perfectly reasonable and would actually be expected by anyone familiar with Gradle: `gradle test` should run the tests. In other words, developers should not be forced to execute `gradle check` or `gradle build` just to run JUnit 5 tests.

**Comment by sbrannen** [comment]
> 'check' which itself is a dependency of 'test'

It's the other way around: `check` depends on `test`. See the documentation for the [java plugin](https://docs.gradle.org/current/userguide/java_plugin.html) for details.

In any case, before my changes executing `gradle test` did _not_ execute the `junit5Test` task. :wink:

**Comment by sbrannen** [comment]
> Maybe we should enable that behavior by default?

Yes, I fully agree!

However, I didn't want to rewrite the `JUnit5Plugin` just to get this working within our build. The task dependency configuration within `JUnit5Plugin` needs to be addressed separately.

**Comment by jlink** [comment]
Yes, but 'check' did. See my earlier comments why I chose to do it that way.

2016-01-04 15:28 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by sbrannen** [comment]
> Yes, but 'check' did.

I never made any argument to the contrary.

As I stated previously, developers should not be forced to execute `gradle check` or `gradle build` just to run JUnit 5 tests.

**Comment by jlink** [comment]
"developers should not be forced to execute gradle check or gradle build
just to run JUnit 5 tests"

Why not? The "test" task is a built-in gradle task tightly woven into how
the java-plugin works. As long as JUnit5 is not a first-class citizen (in
the same way as JUnit4 and TestNG), JUnit5 should IMO work as all other
"checking type" plugins.

 A developer that has decided to juse JUnit5 in this early Alpha stage is
perfectly capable of calling "junit5Test" instead of "test" if they want to
run the tests only.


2016-01-04 15:35 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by sbrannen** [comment]
I have updated both the title and description of this issue to clarify the scope of this issue.

If somebody wants to discuss the feature set of the `JUnit5Plugin`, please open a separate GitHub issue to address that topic.
